name: Generate site & deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: go get
        working-directory: ./generator
      - name: Prepare output directory
        run: |
          rm -rf out
          mkdir -p out
          chmod -R u+w out
      - name: Debug Permissions
        run: |
          ls -l
          whoami
      - name: Generate Site
        shell: bash
        run: sh run.sh --verbose
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: out

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
